MxOnline2/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
import users.urls, organization.urls, course.urls
from users.views import IndexView, LoginView, LogoutView, RegisterView, ActiveUserView, ForgetPwdView, ResetPwdView, ModifyPwdView
from django.views.static import serve
from MxOnline2.settings import MEDIA_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    re_path('active/(?P<active_code>.*)/', ActiveUserView.as_view(), name='active_user'),
    path('forget/', ForgetPwdView.as_view(), name='forget_pwd'),
    re_path('reset/(?P<reset_code>.*?)/', ResetPwdView.as_view(), name='reset_pwd'),
    path('modify_pwd/', ModifyPwdView.as_view(), name='modify_pwd'),
    path('captcha/', include('captcha.urls')),

    # 配置图片路径、静态文件路径
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),

    path('users/', include(users.urls, namespace='users')),
    path('organization/', include(organization.urls, namespace='organization')),
    path('course/', include(course.urls, namespace='course')),
    # 富文本ckeditor配置url
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

handler404 = 'users.views.pag_not_found'
handler500 = 'users.views.page_error'

apps/course/urls.py
# coding:utf-8
from django.urls import path, re_path
from .views import CourseView, CourseListView, CourseInfoView, CourseCommentView, AddCommentView, VideoPlayView


app_name = 'course'

urlpatterns = [
    path('list/', CourseListView.as_view(), name='course_list'),
    re_path('course/(?P<course_id>\d+)/', CourseView.as_view(), name='course_detail'),
    re_path('info/(?P<course_id>\d+)/', CourseInfoView.as_view(), name='course_info'),
    re_path('comment/(?P<course_id>\d+)/', CourseCommentView.as_view(), name='course_comment'),
    path('add_comment/', AddCommentView.as_view(), name='add_comment'),
    re_path('video/(?P<video_id>\d+)/', VideoPlayView.as_view(), name='video_play'),
]

apps/organization/urls.py
# coding:utf-8
from django.urls import path, re_path
from .views import OrgListView, AddUserAskView, OrgDetailHomeView, OrgDetailCourseView, OrgDetailTeacherView,\
    OrgDetailDescView, AddFavView, TeacherListView, TeacherDetailView


app_name = 'organization'

urlpatterns = [
    path('list/', OrgListView.as_view(), name='organization_list'),
    path('add_ask/', AddUserAskView.as_view(), name='add_ask'),
    path('add_fav', AddFavView.as_view(), name='add_fav'),
    re_path('home/(?P<org_id>\d+)/', OrgDetailHomeView.as_view(), name='org_detail_home'),
    re_path('course/(?P<org_id>\d+)/', OrgDetailCourseView.as_view(), name='org_detail_course'),
    re_path('org_teacher/(?P<org_id>\d+)/', OrgDetailTeacherView.as_view(), name='org_detail_teacher'),
    re_path('desc/(?P<org_id>\d+)/', OrgDetailDescView.as_view(), name='org_detail_desc'),
    path('teacher/list/', TeacherListView.as_view(), name='teacher_list'),
    re_path('teacher/detail/(?P<teacher_id>\d+)/', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/course/models.py
from django.db import models
from datetime import datetime
from organization.models import Organization, Teacher
from django.utils.html import format_html
from ckeditor.fields import RichTextField


# Create your models here.
class Course(models.Model):
    DEGREE_CHOICES = (
        ('cj', '初级'),
        ('zj', '中级'),
        ('gj', '高级'),
    )
    organization = models.ForeignKey(Organization, verbose_name="所属机构", on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, verbose_name="授课教师", on_delete=models.CASCADE)
    name = models.CharField(verbose_name="名称", max_length=50)
    desc = models.CharField(verbose_name="课程描述", max_length=255)
    detail = RichTextField(null=True, blank=True)
    image = models.ImageField(verbose_name="封面图", upload_to='course/%Y/%m')
    degree = models.CharField(verbose_name="难度", choices=DEGREE_CHOICES, max_length=2, default='cj')
    is_banner = models.BooleanField(verbose_name="是否轮播", default=False)
    learn_times = models.IntegerField(verbose_name="课程时长(分钟数)", default=0)
    click_nums = models.IntegerField(verbose_name="点击数", default=0)
    learn_nums = models.IntegerField(verbose_name="学习人数", default=0)
    fav_nums = models.IntegerField(verbose_name="收藏数", default=0)
    category = models.CharField(verbose_name="分类", max_length=20)
    tag = models.CharField(verbose_name="标签", max_length=20)
    you_need_know = models.CharField(verbose_name="课程须知", max_length=255, default="本课程需要静心阅读")
    teacher_tell = models.CharField(verbose_name="老师告诉你", max_length=255, default="好好学习，天天向上")
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    # 设置某个字段的颜色
    def colored_degree(self):
        if self.degree == 'cj':
            color_code = 'green'
        elif self.degree == 'zj':
            color_code = 'yellow'
        elif self.degree == 'gj':
            color_code = 'red'
        return format_html(
            '<span style="color: {};">{}</span>',
            color_code,
            self.degree,
        )

    # short_description functions like a model field's verbose_name
    # 此方法用于自定义某个函数字段的标题
    colored_degree.short_description = u'难度'

    class Meta:
        verbose_name = "课程"
        verbose_name_plural = verbose_name

    # 获取当前课程的所有章节
    def get_lessons(self):
        return self.lesson_set.all()

    def get_resources(self):
        return self.courseresource_set.all()

    def get_lesson_nums(self):
        return self.lesson_set.all().count()

    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    def __str__(self):
        return self.name


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name="所属课程", on_delete=models.CASCADE)
    name = models.CharField(verbose_name="章节名", max_length=20)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    class Meta:
        verbose_name = "章节"
        verbose_name_plural = verbose_name

    def __str__(self):
        return '《{0}》课程的章节 >> {1}'.format(self.course, self.name)

    def get_videos(self):
        return self.video_set.all()


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name="所属章节", on_delete=models.CASCADE)
    name = models.CharField(verbose_name="视频名", max_length=20)
    # 这里的视频地址是否可以替换为一个FileField？
    url = models.URLField(verbose_name="视频地址", max_length=200, default='')
    learn_times = models.IntegerField(verbose_name="视频时长(分钟数)", default=0)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    class Meta:
        verbose_name = "视频"
        verbose_name_plural = verbose_name

    def __str__(self):
        return '《{0}》章节的视频 >> {1}'.format(self.lesson, self.name)


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name="所属课程", on_delete=models.CASCADE)
    name = models.CharField(verbose_name="资源名", max_length=20)
    resource = models.FileField(verbose_name="资源文件", upload_to='course/resource/%Y%m')
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    class Meta:
        verbose_name = "课程资源"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/course/views.py
from django.shortcuts import render
from django.views.generic import View
from .models import Course, Video
from operation.models import UserFavorite, CourseComment, UserCourse
from django.core.paginator import Paginator
from django.http import HttpResponse
from utils.mixin_utils import LoginRequiredMixin
from django.db.models import Q


class CourseListView(View):
    def get(self, request):
        all_courses = Course.objects.all()

        hot_courses = all_courses.order_by('-click_nums')[:5]

        # sort
        sort = request.GET.get('sort', '')
        if sort == 'hot':
            all_courses = all_courses.order_by('-click_nums')
        elif sort == 'students':
            all_courses = all_courses.order_by('-learn_nums')

        # 搜索功能，使用icontain查询
        search_keywords = request.GET.get('keywords', '')
        if search_keywords:
            all_courses = all_courses.filter(Q(name__icontains=search_keywords) | Q(desc__icontains=search_keywords) | Q(detail__icontains=search_keywords))

        # 翻页功能
        paginator = Paginator(all_courses, 3)
        page = request.GET.get('page')
        all_courses = paginator.get_page(page)

        context = {
            'all_courses': all_courses,
            'hot_courses': hot_courses,
            'sort': sort,
        }
        return render(request, 'course/course_list.html', context=context)


# Create your views here.
class CourseView(View):
    def get(self, request, course_id):
        course = Course.objects.get(id=int(course_id))
        organization = course.organization
        # 课程点击数+1
        course.click_nums += 1
        course.save()

        # 用户收藏功能，如果用户未登录，显示未收藏；用户已登录，可根据用户的收藏数据判断
        has_fav_course = False
        has_fav_org = False

        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user, fav_id=course.id, fav_type=2):
                has_fav_course = True
            if UserFavorite.objects.filter(user=request.user, fav_id=organization.id, fav_type=1):
                has_fav_org = True

        # 相关课程推荐为根据标签推荐，需要排除自身
        tag = course.tag
        all_related_courses = Course.objects.filter(tag=tag)[:5]
        # 移除当前课程。待修改
        related_courses = all_related_courses

        context = {
            'course': course,
            'organization': organization,
            'related_courses': related_courses,
            'has_fav_course': has_fav_course,
            'has_fav_org': has_fav_org,
        }
        return render(request, 'course/course_detail.html', context=context)


class CourseInfoView(LoginRequiredMixin, View):
    def get(self, request, course_id):
        course = Course.objects.get(id=int(course_id))
        teacher = course.teacher

        # 关联数据，如果用户未学习该课程，则新建
        user_course = UserCourse.objects.filter(user=request.user, course=course)
        if not user_course:
            UserCourse.objects.create(user=request.user, course=course)

        # 获取用户相关课程的方法：
        # 首先，获取所有course=当前课程的usercourse，在这些usercourse中获取所有用户的id
        # 其次，通过user_ids获取这些用户学过的所有usercourse，在其中获取所有的课程id
        # 然后，通过course_ids获取所有课程
        user_courses = UserCourse.objects.filter(course=course)
        user_ids = [user_course.user_id for user_course in user_courses]
        # __in方法获取一个列表中的数据，filter查找所有匹配的对象
        all_user_courses = UserCourse.objects.filter(user_id__in=user_ids)
        course_ids = [all_user_course.course_id for all_user_course in all_user_courses]
        related_courses = Course.objects.filter(id__in=course_ids).order_by('-click_nums')[:5]

        context = {
            'course': course,
            'teacher': teacher,
            'related_courses': related_courses,
        }
        return render(request, 'course/course_video.html', context=context)


class CourseCommentView(LoginRequiredMixin, View):
    def get(self, request, course_id):
        course = Course.objects.get(id=int(course_id))
        teacher = course.teacher
        all_comments = course.coursecomment_set.all()

        # 关联数据，如果用户未学习该课程，则新建
        user_course = UserCourse.objects.filter(user=request.user, course=course)
        if not user_course:
            UserCourse.objects.create(user=request.user, course=course)

        # 获取用户相关课程的方法：
        # 首先，获取所有course=当前课程的usercourse，在这些usercourse中获取所有用户的id
        # 其次，通过user_ids获取这些用户学过的所有usercourse，在其中获取所有的课程id
        # 然后，通过course_ids获取所有课程
        user_courses = UserCourse.objects.filter(course=course)
        user_ids = [user_course.user_id for user_course in user_courses]
        # __in方法获取一个列表中的数据，filter查找所有匹配的对象
        all_user_courses = UserCourse.objects.filter(user_id__in=user_ids)
        course_ids = [all_user_course.course_id for all_user_course in all_user_courses]
        related_courses = Course.objects.filter(id__in=course_ids).order_by('-click_nums')[:5]

        context = {
            'course': course,
            'teacher': teacher,
            'all_comments': all_comments,
            'related_courses': related_courses,
        }
        return render(request, 'course/course_comment.html', context=context)


class AddCommentView(View):
    def post(self, request):
        if not request.user.is_authenticated:
            return HttpResponse('{"status":"fail", "msg":"用户未登录"}', content_type='application/json')
        course_id = request.POST.get("course_id", 0)
        comment = request.POST.get("comments", "")
        if int(course_id) > 0 and comment:
            # 实例化一个course_comments对象
            course_comment = CourseComment()
            course = Course.objects.get(id=int(course_id))
            # 保存到数据库
            course_comment.course = course
            course_comment.user = request.user
            course_comment.comment = comment
            course_comment.save()
            return HttpResponse('{"status": "success", "msg": "评论成功"}', content_type='application/json')
        else:
            return HttpResponse('{"status": "fail", "msg": "评论失败"}', content_type='application/json')


class VideoPlayView(View):
    def get(self, request, video_id):
        video = Video.objects.get(id=int(video_id))
        course = video.lesson.course

        course.learn_nums += 1
        course.save()

        # 关联数据，如果用户未学习该课程，则新建
        user_course = UserCourse.objects.filter(user=request.user, course=course)
        if not user_course:
            UserCourse.objects.create(user=request.user, course=course)

        user_courses = UserCourse.objects.filter(course=course)
        user_ids = [user_course.user_id for user_course in user_courses]
        # __in方法获取一个列表中的数据，filter查找所有匹配的对象
        all_user_courses = UserCourse.objects.filter(user_id__in=user_ids)
        course_ids = [all_user_course.course_id for all_user_course in all_user_courses]
        related_courses = Course.objects.filter(id__in=course_ids).order_by('-click_nums')[:5]

        context = {
            'video': video,
            'course': course,
            'related_courses': related_courses,
        }
        return render(request, 'course/course_play.html', context=context)

templates/course/course_comment.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Simon|课程详情{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/course-comment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
{% endblock %}
{% block custom_bread %}
<section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
				<li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                <li>章节评论</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}
{% block content %}
<div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_times }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.learn_nums }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active " id="learnOn"  href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
                            <li><a id="commentOn" class="active" href="{% url 'course:course_comment' course.id %}"><span>评论</span></a></li>
                        </ul>
                    </div>

                    <!--发布评论-->
                    <div id="js-pub-container" class="issques clearfix js-form">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！" ></textarea>
                        </div>
                        <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                        <p class="global-errortip js-global-error"></p>
                    </div>
                    <div id="course_note">
                        <ul class="mod-post" id="comment-list">
                            {% for comment in all_comments %}
                            <li class="post-row">
                                <div class="media">
                                    <span target="_blank"><img src='{{ MEDIA_URL }}{{ comment.user.image }}' width='40' height='40' /></span>
                                </div>
                                <div class="bd">
                                    <div class="tit">
                                        <span target="_blank">{{ comment.user.name }}</span>
                                    </div>
                                    <p class="cnt">{{ comment.comment }}</p>
                                    <div class="footer clearfix">
                                        <span title="创建时间" class="l timeago">时间：{{ comment.add_time }}</span>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>

                </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for resource in course.get_resources %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ resource.resource }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ teacher.image }}' width='80' height='80' />
                            </a>
                        <span class="tit">
                          <a href="/u/315464/courses?sort=publish" target="_blank">{{ teacher.name }}</a>
                        </span>
                            <span class="job">{{ teacher.points }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.you_need_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                                    {% for related_course in related_courses %}
                                    <li class="curr">
                                        <a href="course_detail.html" target="_blank">
                                            <img src="{{ MEDIA_URL }}{{ related_course.image }}" alt="django与vuejs实战项目2">
                                            <span class="name autowrap">{{ related_course.name }}</span>
                                        </a>
                                    </li>
                                    {% endfor %}

                                </ul>
                            </div>
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                <ul class="other-list">
                                    <li class="curr">
                                        <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                            <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg' %}" alt="Java工程师">
                                            <span class="name autowrap">Java工程师</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>    </div>
            </div>
            <div class="clear"></div>

        </div>

    </div>
</div>
{% endblock %}

{% block custom_js %}
<script type="text/javascript">
    //添加评论
    $('#js-pl-submit').on('click', function(){
        var comments = $("#js-pl-textarea").val()
        if(comments == ""){
            alert("评论不能为空")
            return
        }
        $.ajax({
            cache: false,
            type: "POST",
            url:"{% url 'course:add_comment' %}",
            data:{'course_id':{{ course.id }}, 'comments':comments},
            async: true,
            beforeSend:function(xhr, settings){
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function(data) {
                if(data.status == 'fail'){
                    if(data.msg == '用户未登录'){
                        window.location.href="{% url 'login' %}";
                    }else{
                        alert(data.msg)
                    }

                }else if(data.status == 'success'){
                    window.location.reload();//刷新当前页面.
                }
            },
        });
    });

</script>
{% endblock %}

templates/course/course_play.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{{ video.name }}|Simon的慕课{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/video-js.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <style>
        .video-js .vjs-big-play-button{
            top: 50%;
            left: 50%;
        }
    </style>
{% endblock %}

{% block custom_js %}
     <script src="{% static 'js/video.min.js' %}" type="text/javascript"></script>
{% endblock %}

<!--crumbs start-->
{% block custom_bread %}
<section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
				<li><a href="{% url 'course:course_detail' course.id %}">{{ course.name }}</a>></li>
                <li>{{ video.name }}</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}

{% block content %}
<div id="main">
    <div class="course-info-main clearfix w has-progress">
        <div style="width:1200px;height:675px;">
            <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="1200"
                  poster="http://video-js.zencoder.com/oceans-clip.png"
                  data-setup="{}">
                <source src="{{ video.url }}" type='video/mp4'>
            </video>
        </div>
        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
                            <li><a id="commentOn" class="" href="{% url 'course:course_comment' course.id %}"><span>评论</span></a></li>
                        </ul>
                    </div>
                    <div id="notice" class="clearfix">
                        <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a> </div>
                    </div>
                    <div class="mod-chapters">
                        {% for lesson in course.lesson_set.get_queryset %}
                            <div class="chapter chapter-active" >
                                <h3>
                                    <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                                </h3>
                            <ul class="video">

                                {% for video in lesson.video_set.get_queryset  %}
                                <li>
                                    <a target="_blank" href="{% url 'course:video_play' video.id %}" class="J-media-item studyvideo">{{ video.name }} ({{ video.learn_times }})
                                        <i class="study-state"></i>
                                    </a>
                                </li>
                                {% endfor %}

                            </ul>
                        </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="aside r">
                    <div class="bd">
                        <div class="box mb40">
                            <h4>资料下载</h4>
                            <ul class="downlist">
                            {% for resource in course.get_resources %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ resource.resource }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                            </ul>
                        </div>
                        <div class="box mb40">
                            <h4>讲师提示</h4>
                            <div class="teacher-info">
                                <a href="" target="_blank">
                                    <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80' />
                                </a>
                                <span class="tit">
                                  <a href="" target="_blank">{{ course.teacher.name }}</a>
                                </span>
                                <span class="job">{{ course.teacher.work_position }}</span>
                            </div>
                            <div class="course-info-tip">
                                <dl class="first">
                                    <dt>课程须知</dt>
                                    <dd class="autowrap">{{ course.you_need_know }}</dd>
                                </dl>
                                <dl>
                                    <dt>老师告诉你能学到什么？</dt>
                                    <dd class="autowrap">{{ course.teacher_tell }}</dd>
                                </dl>
                            </div>
                        </div>

                        <div class="cp-other-learned  js-comp-tabs">
                            <div class="cp-header clearfix">
                                <h2 class="cp-tit l">该课的同学还学过</h2>
                            </div>
                            <div class="cp-body">
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                    <!-- img 200 x 112 -->
                                    <ul class="other-list">
                                        {% for related_course in related_courses  %}
                                        <li class="curr">
                                            <a href="{% url 'course:course_detail' related_course.id %}" target="_blank">
                                                <img src="{{ MEDIA_URL }}{{ related_course.image }}" alt="{{ related_course.name }}">
                                                <span class="name autowrap">{{ related_course.name }}</span>
                                            </a>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                    <ul class="other-list">

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clear">
            </div>
        </div>
    </div>
</div>
{% endblock %}