MxOnline2/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
import users.urls, organization.urls, course.urls
from users.views import IndexView, LoginView, LogoutView, RegisterView, ActiveUserView, ForgetPwdView, ResetPwdView, ModifyPwdView
from django.views.static import serve
from MxOnline2.settings import MEDIA_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    re_path('active/(?P<active_code>.*)/', ActiveUserView.as_view(), name='active_user'),
    path('forget/', ForgetPwdView.as_view(), name='forget_pwd'),
    re_path('reset/(?P<reset_code>.*?)/', ResetPwdView.as_view(), name='reset_pwd'),
    path('modify_pwd/', ModifyPwdView.as_view(), name='modify_pwd'),
    path('captcha/', include('captcha.urls')),

    # 配置图片路径、静态文件路径
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),

    path('users/', include(users.urls, namespace='users')),
    path('organization/', include(organization.urls, namespace='organization')),
    path('course/', include(course.urls, namespace='course')),
    # 富文本ckeditor配置url
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

handler404 = 'users.views.pag_not_found'
handler500 = 'users.views.page_error'

apps/course/urls.py
# coding:utf-8
from django.urls import path, re_path
from .views import CourseView, CourseListView, CourseInfoView, CourseCommentView, AddCommentView, VideoPlayView


app_name = 'course'

urlpatterns = [
    path('list/', CourseListView.as_view(), name='course_list'),
    re_path('course/(?P<course_id>\d+)/', CourseView.as_view(), name='course_detail'),
    re_path('info/(?P<course_id>\d+)/', CourseInfoView.as_view(), name='course_info'),
    re_path('comment/(?P<course_id>\d+)/', CourseCommentView.as_view(), name='course_comment'),
    path('add_comment/', AddCommentView.as_view(), name='add_comment'),
    re_path('video/(?P<video_id>\d+)/', VideoPlayView.as_view(), name='video_play'),
]

apps/organization/urls.py
# coding:utf-8
from django.urls import path, re_path
from .views import OrgListView, AddUserAskView, OrgDetailHomeView, OrgDetailCourseView, OrgDetailTeacherView,\
    OrgDetailDescView, AddFavView, TeacherListView, TeacherDetailView


app_name = 'organization'

urlpatterns = [
    path('list/', OrgListView.as_view(), name='organization_list'),
    path('add_ask/', AddUserAskView.as_view(), name='add_ask'),
    path('add_fav', AddFavView.as_view(), name='add_fav'),
    re_path('home/(?P<org_id>\d+)/', OrgDetailHomeView.as_view(), name='org_detail_home'),
    re_path('course/(?P<org_id>\d+)/', OrgDetailCourseView.as_view(), name='org_detail_course'),
    re_path('org_teacher/(?P<org_id>\d+)/', OrgDetailTeacherView.as_view(), name='org_detail_teacher'),
    re_path('desc/(?P<org_id>\d+)/', OrgDetailDescView.as_view(), name='org_detail_desc'),
    path('teacher/list/', TeacherListView.as_view(), name='teacher_list'),
    re_path('teacher/detail/(?P<teacher_id>\d+)/', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/organization/models.py
from django.db import models
from datetime import datetime


# Create your models here.
'''
points:
1、verbose_name的作用是给予对象一个人类可读的名字，”A human-readable name for the object“。
用于table中某个字段时，在admin后台会显示verbose_name，用于Meta中时，显示的是当前数据表的名称。
2、max_length为最大字符长度，由于CharField在数据库中对应为varchar，最大长度为255，
所以这里设置的最大值也不能超过255，否则，用TextField代替。max_length的计算方法:len("字符串")=3。
3、ImageField继承自FileField，用于上传文件，其中的upload_to属性，用于指定上传文件的目录，该目录会在MEDIA_ROOT下自动生成。
如使用upload_to='uploads/%Y/%m/%d/'，文件会上传到MEDIA_ROOT/uploads/2015/01/30中，
/%Y/%m/%d/为strftime()格式化的xxxx年xx月xx日。
4、null=True和blank=True通常一起使用，null代表数据库可以为空，blank代表后台表单数据填写时可以留白。
5、choices用于选择框，在使用前应该在class中定义一个可迭代对象，[(A, B), (A, B) ...]，每个元组中第一个
元素代表实际值，第二个是人类可读名称，类似于verbose_name。
'''


class City(models.Model):
    name = models.CharField(verbose_name="城市", max_length=20)
    desc = models.CharField(verbose_name="描述", max_length=255)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    class Meta:
        verbose_name = "城市"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Organization(models.Model):
    ORG_CHOICES = (
        ('pxjg', '培训机构'),
        ('gx', '高校'),
        ('gr', '个人'),
    )

    name = models.CharField(verbose_name="机构名称", max_length=20)
    desc = models.TextField(verbose_name="机构描述")
    category = models.CharField(verbose_name="机构类别", max_length=20, choices=ORG_CHOICES, default='pxjg')
    tag = models.CharField(verbose_name="机构标签", max_length=20, default="全国知名")
    image = models.ImageField(verbose_name="封面图", upload_to='organization/%Y/%m')
    address = models.CharField(verbose_name="机构地址", max_length=200)
    city = models.ForeignKey(City, verbose_name="所在城市", on_delete=models.CASCADE)
    click_nums = models.IntegerField(verbose_name="点击数", default=0)
    learn_nums = models.IntegerField(verbose_name="学习人数", default=0)
    fav_nums = models.IntegerField(verbose_name="收藏数", default=0)
    course_nums = models.IntegerField(verbose_name="课程数", default=0)
    is_authentication = models.BooleanField(verbose_name="是否认证", default=False)
    is_gold = models.BooleanField(verbose_name="金牌机构", default=False)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    class Meta:
        verbose_name = "课程机构"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    # 定义一个方法，可以获取当前机构的课程数目和教师数目
    # 也可以在view中写，但是重复造轮子，每次调用都要写，写在模型里方便调用
    def get_course_nums(self):
        return self.course_set.all().count()

    def get_teacher_nums(self):
        return self.teacher_set.all().count()


class Teacher(models.Model):
    organization = models.ForeignKey(Organization, verbose_name="所属机构", on_delete=models.CASCADE)
    name = models.CharField(verbose_name="姓名", max_length=20)
    age = models.IntegerField(verbose_name="年龄", default=0)
    image = models.ImageField(verbose_name="头像", upload_to='teacher/%Y/%m', default='', null=True, blank=True)
    work_year = models.IntegerField(verbose_name="工作年限", default=0)
    work_company = models.CharField(verbose_name="就职公司", max_length=50)
    work_position = models.CharField(verbose_name="工作岗位", max_length=50)
    points = models.CharField(verbose_name="教学特点", max_length=50)
    click_nums = models.IntegerField(verbose_name="点击数", default=0)
    fav_nums = models.IntegerField(verbose_name="收藏数", default=0)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.now)

    class Meta:
        verbose_name = "教师"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_course_nums(self):
        return self.course_set.all().count()

apps/organization/forms.py
import re
from django import forms
from operation.models import UserAsk


# 由于我们在UserAs模型中定义了该字段，所以此处不用再重新写一个Form，而是引用ModelForm。
# ModelForm的用法：先自定义一个继承自ModelForm的子类，然后在其中设置Meta元类，定义model属性为要关联的ORM模型
# 在fields中定义form表单中使用的字段,字段名必须是Model中的字段名.
# 另外，fields还有两个属性：fields = '__all__'和exclude = ['title']，分别代表引入所有字段和除掉某字段
class UserAskForm(forms.ModelForm):
    class Meta:
        model = UserAsk
        fields = ['name', 'mobile', 'course_name']

    def clean_mobile(self):
        mobile = self.cleaned_data['mobile']
        REGEX_MOBILE = "^1[358]\d{9}$|^147\d{8}$|176\d{8}$"
        pattern = re.compile(REGEX_MOBILE)
        if pattern.match(mobile):
            return mobile
        else:
            raise forms.ValidationError('手机号码非法', code='mobile_invalid')

apps/organization/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View
from .models import City, Organization, Teacher
from course.models import Course
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import UserAskForm
from operation.models import UserAsk, UserFavorite
from django.db.models import Q


# Create your views here.
class OrgListView(View):
    def get(self, request):
        all_cities = City.objects.all()
        all_organizations = Organization.objects.all()

        hot_organizations = all_organizations.order_by('-click_nums')[:5]

        # 分类筛选
        category_id = request.GET.get('ct', '')
        if category_id:
            all_organizations = all_organizations.filter(category=category_id)

        # 城市筛选
        city_id = request.GET.get('city', '')
        if city_id:
            all_organizations = all_organizations.filter(city=int(city_id))

        # 搜索功能，使用icontain查询
        search_keywords = request.GET.get('keywords', '')
        if search_keywords:
            all_organizations = all_organizations.filter(
                Q(name__icontains=search_keywords) | Q(desc__icontains=search_keywords))

        # 排序筛选
        sort_id = request.GET.get('sort', '')
        if sort_id == 'students':
            all_organizations = all_organizations.order_by('-learn_nums')
        elif sort_id == 'courses':
            all_organizations = all_organizations.order_by('-course_nums')

        course_org_nums = all_organizations.count()

        # 翻页功能
        paginator = Paginator(all_organizations, 3)
        page = request.GET.get('page')
        # try:
        #         #     # 获取页码内的列表信息
        #         #     organizations = paginator.page(page)
        #         # except PageNotAnInteger:
        #         #     # 如果用户请求的页码不是整数，显示第一页
        #         #     organizations = paginator.page(1)
        #         # except EmptyPage:
        #         #     # 如果用户请求的页码超过最大页码，显示最后一页
        #         #     organizations = paginator.page(paginator.num_pages)
        organizations = paginator.get_page(page)

        context = {
            'all_cities': all_cities,
            'all_organizations': organizations,
            'hot_organizations': hot_organizations,
            'course_org_nums': course_org_nums,
            'category_id': category_id,
            'city_id': city_id,
            'sort_id': sort_id,
            'search_keywords': search_keywords,
        }
        return render(request, 'organization/org_list.html', context=context)


class AddUserAskView(View):
    def post(self, request):
        userask_form = UserAskForm(request.POST)
        if userask_form.is_valid():
            # 将form内容保存至UserAskModel，这里使用commit=True参数会将数据保存，为False则不保存至db。
            # user_ask是一个instance：userask_form类ModelForm所映射的数据库模型，即UserAskForm
            # 如果该对象已创建，则更新；如果该对象未创建，则新建。
            user_ask = userask_form.save(commit=True)
            return HttpResponse('{"status":"success"}', content_type='application/json')
        else:
            return HttpResponse('{"status":"fail", "msg":"添加出错"}', content_type='application/json')


class AddFavView(View):
    def post(self, request):
        # 如果用户未登录，则提示用户未登录，ajax
        if not request.user.is_authenticated:
            return HttpResponse({'status': 'fail', 'msg': '用户未登录'}, content_type='application/json')

        # 获取收藏id即类型，如果数据库中已存在，那么取消收藏，并且收藏数-1
        id = request.POST.get('fav_id', None)
        type = request.POST.get('fav_type', None)
        if id and type:
            exist_record = UserFavorite.objects.filter(user=request.user, fav_id=int(id), fav_type=int(type))
            if exist_record:
                exist_record.delete()
                if int(type) == 1:
                    org = Organization.objects.get(id=int(id))
                    org.fav_nums -= 1
                    if org.fav_nums < 0:
                        org.fav_nums = 0
                    org.save()
                elif int(type) == 2:
                    course = Course.objects.get(id=int(id))
                    course.fav_nums -= 1
                    if course.fav_nums < 0:
                        course.fav_nums = 0
                    course.save()
                elif int(type) == 3:
                    teacher = Teacher.objects.get(id=int(id))
                    teacher.fav_nums -= 1
                    if teacher.fav_nums < 0:
                        teacher.fav_nums = 0
                    teacher.save()
                return HttpResponse({'status': 'success', 'msg': '收藏'}, content_type='application/json')
            else:
                user_fav = UserFavorite()
                user_fav.user = request.user
                user_fav.fav_id = int(id)
                user_fav.fav_type = int(type)
                user_fav.save()

                # 收藏数+1
                if int(type) == 1:
                    org = Organization.objects.get(id=int(id))
                    org.fav_nums += 1
                    org.save()
                elif int(type) == 2:
                    course = Course.objects.get(id=int(id))
                    course.fav_nums += 1
                    course.save()
                elif int(type) == 3:
                    teacher = Teacher.objects.get(id=int(id))
                    teacher.fav_nums += 1
                    teacher.save()

                return HttpResponse({'status': 'success', 'msg': '已收藏'}, content_type='application/json')
        else:
            return HttpResponse({'status': 'fail', 'msg': '收藏出错'}, content_type='application/json')


class OrgDetailHomeView(View):
    def get(self, request, org_id):
        organization = Organization.objects.get(id=int(org_id))
        organization.click_nums += 1
        organization.save()
        # ForeignKey的反向查询用_set方法
        all_courses = organization.course_set.all()[:4]
        all_teachers = organization.teacher_set.all()[:4]
        current = 'home'

        has_fav = False
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user, fav_id=organization.id, fav_type=1):
                has_fav = True

        context = {
            'organization': organization,
            'all_courses': all_courses,
            'all_teachers': all_teachers,
            'current': current,
            'has_fav': has_fav,
        }
        return render(request, 'organization/org_detail_home.html', context=context)


class OrgDetailCourseView(View):
    def get(self, request, org_id):
        organization = Organization.objects.get(id=int(org_id))
        # ForeignKey的反向查询用_set方法
        all_courses = organization.course_set.all()

        # 翻页功能
        paginator = Paginator(all_courses, 3)
        page = request.GET.get('page')
        all_courses = paginator.get_page(page)

        has_fav = False
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user, fav_id=organization.id, fav_type=1):
                has_fav = True

        current = 'course'
        context = {
            'organization': organization,
            'all_courses': all_courses,
            'current': current,
            'has_fav': has_fav,
        }
        return render(request, 'organization/org_detail_course.html', context=context)


class OrgDetailTeacherView(View):
    def get(self, request, org_id):
        organization = Organization.objects.get(id=int(org_id))
        # ForeignKey的反向查询用_set方法
        all_teachers = organization.teacher_set.all()

        # 翻页功能
        paginator = Paginator(all_teachers, 3)
        page = request.GET.get('page')
        all_teachers = paginator.get_page(page)

        has_fav = False
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user, fav_id=organization.id, fav_type=1):
                has_fav = True

        current = 'teacher'
        context = {
            'organization': organization,
            'all_teachers': all_teachers,
            'current': current,
            'has_fav': has_fav,
        }
        return render(request, 'organization/org_detail_teacher.html', context=context)


class OrgDetailDescView(View):
    def get(self, request, org_id):
        organization = Organization.objects.get(id=int(org_id))
        # ForeignKey的反向查询用_set方法
        current = 'desc'

        # 收藏状态
        has_fav = False
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user, fav_id=organization.id, fav_type=1):
                has_fav = True

        context = {
            'organization': organization,
            'current': current,
            'has_fav': has_fav,
        }
        return render(request, 'organization/org_detail_desc.html', context=context)


class TeacherListView(View):
    def get(self, request):
        all_teachers = Teacher.objects.all()

        teacher_nums = all_teachers.count()

        # 搜索功能，使用icontain查询
        search_keywords = request.GET.get('keywords', '')
        if search_keywords:
            all_teachers = all_teachers.filter(name__icontains=search_keywords)

        sort = request.GET.get('sort', '')
        if sort == 'hot':
            all_teachers = all_teachers.order_by('-click_nums')

        # 翻页功能
        paginator = Paginator(all_teachers, 3)
        page = request.GET.get('page')
        teachers = paginator.get_page(page)

        hot_teachers = all_teachers.order_by('-click_nums')[:8]
        context = {
            'all_teachers': teachers,
            'teacher_nums': teacher_nums,
            'hot_teachers': hot_teachers,
            'sort': sort,
            'search_keywords': search_keywords,
        }
        return render(request, 'organization/teacher_list.html', context=context)


class TeacherDetailView(View):
    def get(self, request, teacher_id):
        teacher = Teacher.objects.get(id=int(teacher_id))

templates/organization/org_detail_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}Simon|机构首页{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block custom_js %}{% endblock %}
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>联系我们：<b>xxxxxxxx@gmail.com</b></p></div>
                    {% if request.user.is_authenticated %}
                    <!-- 如果用户已登录成功，则显示其个人中心 -->
                    <div class="personal">
                        <dl class="user fr">
                            <dd>{{ request.user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                            <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                        </dl>
                        <div class="userdetail">
                            <dl>
                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                                <dd>
                                    <h2>{{ request.user.nick_name }}</h2>
                                    <p>{{ request.user.username }}</p>
                                </dd>
                            </dl>
                            <div class="btn">
                                <a class="personcenter fl" href="">进入个人中心</a>
                                <a class="fr" href="{% url 'logout' %}">退出</a>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <!-- 如果用户尚未登录，则显示注册/登录按钮 -->
                    <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                    <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}
                </div>
            </div>

            <div class="middle companyheader">
                <div class="wp">
                    <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ organization.image }}"/>
                    <div class="head fl">
                        <h1>
                            {{ organization.name }}
                            {% if organization.is_auhtentication %}
                                <img src="{% static 'images/authentication.png' %}"/>
                            {% endif %}
                            {% if organization.is_gold %}
                                <img src="{% static 'images/gold.png' %}"/>
                            {% endif %}
                        </h1>
                        <p class="fl">
                            <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                            <span class="precision company-credit" data-star-scope="5.0"></span>
                            <span class="key">5.0</span>
                        </p>
                    </div>
                    <div class="btn fr collectionbtn  notlogin" data-favid="22" data-fav-type="1">
                        {% if has_fav %}
                            已收藏
                        {% else %}
                            收藏
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </header>
</section>

<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
			<li><a href="{% url 'organization:organization_list' %}">课程机构</a>></li>
			<li>{% block page_path %}机构首页{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% if current == 'home' %}active2{% endif %}"><a href="{% url 'organization:org_detail_home' organization.id %}">机构首页</a></li>
                <li class="{% if current == 'course' %}active2{% endif %}"><a href="{% url 'organization:org_detail_course' organization.id %}">机构课程</a></li>
                <li class="{% if current == 'desc' %}active2{% endif %}"><a href="{% url 'organization:org_detail_desc' organization.id %}">机构介绍</a></li>
                <li class="{% if current == 'teacher' %}active2{% endif %}"><a href="{% url 'organization:org_detail_teacher' organization.id %}">机构讲师</a></li>
			</ul>
		</div>
        {% block right_content %}
        {% endblock %}
    </div>
</section>

<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->

<!--header start-->
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'organization:add_fav' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="{% url 'login' %}";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), {{ organization.id }}, 1);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static "images/" %}',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>

<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>

templates/organization/org_detail_home.html
{% extends 'organization/org_detail_base.html' %}
{% load staticfiles %}

{% block title %}Simon|机构首页{% endblock %}
{% block page_path %}机构首页{% endblock %}
{% block right_content %}
<div class="right companycenter layout grouping" >
    <div class="head">
        <h1>全部课程</h1>
        <a class="green fr more" href="{% url 'organization:org_detail_course' organization.id %}">查看更多  >  </a>
    </div>
    <div class="brief group_list">
        {% for course in all_courses %}
            <div class="module1_5 box">
                <a href="{% url 'course:course_detail' course.id %}"><img width="214" src="{{ MEDIA_URL }}{{ course.image }}"/></a>
                <div class="des">
                    <a href="{% url 'course:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                    <span class="fl">课时：<i class="key">{{ course.learn_times }}</i></span>
                    <span class="fr">参加人数：{{ course.learn_nums }}</span>
                </div>
                <div class="bottom">
                    <span class="fl">{{ course.organization.name }}</span>
                     <span class="star fr  notlogin
                        " data-favid="13"  data-fav-type="4">
                        {{ course.organization.fav_nums }}
                    </span>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
<div class="right companycenter layout" >
    <div class="head">
        <h1>机构教师</h1>
        <a class="green fr more" href="{% url 'organization:org_detail_teacher' organization.id %}">查看更多  >  </a>
    </div>
    {% for teacher in all_teachers %}
    <div class="diarys">
        <div class="module5 share company-diary-box" style="padding:10px 0;">
            <div class="left">
                <img class="pic" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                <p>昵称：{{ teacher.name }}</p>
            </div>
            <div class="right">
                <div class="top">
                    <div class="fl">
                        <a href=""><h1>java开发教程</h1></a>
                        <span>发表于：2015-10-12</span>
                    </div>
                </div>
                <div class="middle" style="border-bottom:0;">课程介绍</div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="right companycenter layout" >
    <div class="head">
        <h1>机构介绍</h1>
        <a class="green fr more" href="{% url 'organization:org_detail_desc' organization.id %}">查看更多  >  </a>
    </div>
    <div class="cont">&nbsp; &nbsp;
        <p>&nbsp; &nbsp;</p>
        {{ organization.desc }}
    </div>
</div>
{% endblock %}