MxOnline2/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
import users.urls, organization.urls, course.urls
from users.views import IndexView, LoginView, LogoutView, RegisterView, ActiveUserView, ForgetPwdView, ResetPwdView, ModifyPwdView
from django.views.static import serve
from MxOnline2.settings import MEDIA_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    re_path('active/(?P<active_code>.*)/', ActiveUserView.as_view(), name='active_user'),
    path('forget/', ForgetPwdView.as_view(), name='forget_pwd'),
    re_path('reset/(?P<reset_code>.*?)/', ResetPwdView.as_view(), name='reset_pwd'),
    path('modify_pwd/', ModifyPwdView.as_view(), name='modify_pwd'),
    path('captcha/', include('captcha.urls')),

    # 配置图片路径、静态文件路径
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),

    path('users/', include(users.urls, namespace='users')),
    path('organization/', include(organization.urls, namespace='organization')),
    path('course/', include(course.urls, namespace='course')),
    # 富文本ckeditor配置url
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

handler404 = 'users.views.pag_not_found'
handler500 = 'users.views.page_error'

apps/course/urls.py
# coding:utf-8
from django.urls import path, re_path
from .views import CourseView, CourseListView, CourseInfoView, CourseCommentView, AddCommentView, VideoPlayView


app_name = 'course'

urlpatterns = [
    path('list/', CourseListView.as_view(), name='course_list'),
    re_path('course/(?P<course_id>\d+)/', CourseView.as_view(), name='course_detail'),
    re_path('info/(?P<course_id>\d+)/', CourseInfoView.as_view(), name='course_info'),
    re_path('comment/(?P<course_id>\d+)/', CourseCommentView.as_view(), name='course_comment'),
    path('add_comment/', AddCommentView.as_view(), name='add_comment'),
    re_path('video/(?P<video_id>\d+)/', VideoPlayView.as_view(), name='video_play'),
]

apps/organization/urls.py
# coding:utf-8
from django.urls import path, re_path
from .views import OrgListView, AddUserAskView, OrgDetailHomeView, OrgDetailCourseView, OrgDetailTeacherView,\
    OrgDetailDescView, AddFavView, TeacherListView, TeacherDetailView


app_name = 'organization'

urlpatterns = [
    path('list/', OrgListView.as_view(), name='organization_list'),
    path('add_ask/', AddUserAskView.as_view(), name='add_ask'),
    path('add_fav', AddFavView.as_view(), name='add_fav'),
    re_path('home/(?P<org_id>\d+)/', OrgDetailHomeView.as_view(), name='org_detail_home'),
    re_path('course/(?P<org_id>\d+)/', OrgDetailCourseView.as_view(), name='org_detail_course'),
    re_path('org_teacher/(?P<org_id>\d+)/', OrgDetailTeacherView.as_view(), name='org_detail_teacher'),
    re_path('desc/(?P<org_id>\d+)/', OrgDetailDescView.as_view(), name='org_detail_desc'),
    path('teacher/list/', TeacherListView.as_view(), name='teacher_list'),
    re_path('teacher/detail/(?P<teacher_id>\d+)/', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/users/urls.py
# coding:utf-8
from django.urls import path, re_path
from users.views import UserInfoView, UploadImageView, UpdatePwdView, \
    MyCourseView, MyFavOrgView, MyFavTeacherView, MyFavCourseView, MyMessageView


app_name = 'users'

urlpatterns = [
    path('info/', UserInfoView.as_view(), name='user_info'),
    path('upload/image/', UploadImageView.as_view(), name='upload_image'),
    path('update/pwd/', UpdatePwdView.as_view(), name='update_pwd'),

    path('mycourse/', MyCourseView.as_view(), name='mycourse'),
    path('myfav/org/', MyFavOrgView.as_view(), name='myfav_org'),
    path('myfav/teacher/', MyFavTeacherView.as_view(), name='myfav_teacher'),
    path('myfav/course/', MyFavCourseView.as_view(), name='myfav_course'),
    path('mymessage/', MyMessageView.as_view(), name='mymessage'),
]

apps/users/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=6)


# 注册页表单多了一个验证码字段captcha，从安装的第三方库django-simple-captcha引入
class RegisterForm(forms.Form):
    email = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=6)
    captcha = CaptchaField(required=True, error_messages={'invalid': '验证码错误'})


class ForgetPwdForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(required=True, error_messages={'invalid': '验证码错误'})


class ResetPwdForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=6)
    password2 = forms.CharField(required=True, min_length=6)


class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nick_name', 'birthday', 'gender', 'address', 'mobile']

templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>链接失效</title>
</head>
<body>
<p style="color: red;">链接失效</p>
</body>
</html>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}Simon|首页{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p>慕课在线：<b>这是一个神奇的网站！</b></p></div>
					<!--登录后跳转-->

					{% if request.user.is_authenticated %}
						<div class="personal">
							<dl class="user fr">
								<dd>{% if request.user.username %}{{ request.user.username }}{% else %}{{ request.user.email }}{% endif %}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
								<dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
							</dl>
							<div class="userdetail">
								<dl>
									<dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
									<dd>
										<h2>{% if request.user.username %}{{ request.user.username }}{% else %}{{ request.user.email }}{% endif %}</h2>
										<p>{{ request.user.nickname }}</p>
									</dd>
								</dl>
								<div class="btn">
									<a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
									<a class="fr" href="{% url 'logout' %}">退出</a>
								</div>
							</div>
						</div>
					{% else %}
					    <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
					    <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
					{% endif %}

				</div>
			</div>
			{% block custom_header %}
            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption"
								{% if '/' == request.path %}data-value="course"> 公开课{% endif %}
								{% if '/course' == request.path|slice:":7" %}data-value="course"> 公开课{% endif %}
								{% if '/organization/teacher/' == request.path|slice:":22" %}data-value="teacher"> 授课教师{% endif %}
								{% if '/organization/list/' == request.path|slice:":19" %}data-value="organization"> 课程机构{% endif %}
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="organization">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>
            
            
			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li class="{% if request.path == '/' %}active{% endif %}" >
								<a href="{% url 'index' %}">首页</a>
							</li>
							<li class="{% if request.path|slice:'8' == '/course/' %}active{% endif %}" >
								<a href="{% url 'course:course_list' %}"> 公开课<img class="hot" src="{% static 'images/nav_hot.png' %}"></a>
							</li>
							<li class="{% if request.path|slice:'22' == '/organization/teacher/' %}active{% endif %}" >
								<a href="{% url 'organization:teacher_list' %}">授课教师</a>
							</li>
							<li class="{% if request.path|slice:'19' == '/organization/list/' %}active{% endif %}" >
								<a href="{% url 'organization:organization_list' %}">授课机构</a>
							</li>
						</ul>
					</div>
				</div>
			</nav>
            {% endblock %}
			</div>
    </header>
</section>

<!--crumbs start-->
{% block custom_bread %}
{% endblock %}

<!--content start-->
{% block content %}
{% endblock %}

<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
					<li class="code"><img src="{% static 'images/code.jpg' %}"/><p class="center">扫描关注微信</p></li>
					<li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/><p class="tell">33333333</p><p class="time">周一至周日 9:00-18:00</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
                <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
			</div>
		</div>
	</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
{% block custom_js %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Simon|网站首页{% endblock %}

{% block custom_bread %}
{% endblock %}

<!--content start-->
{% block content %}
<!--banner start-->
<div class="banner">
    <div class="wp">
        <div class="fl">
            <div class="imgslide">
                <ul class="imgs">
                    {% for banner in all_banners %}
                    <li>
                        <a href="{{ banner.url }}">
                            <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="unslider-arrow prev"></div>
            <div class="unslider-arrow next"></div>
        </div>
    </div>
</div>
<!--banner end-->
<!--feature start-->
<section>
    <div class="wp">
        <ul class="feature">
            <li class="feature1">
                <img class="pic" src="{% static 'images/feature1.png' %}"/>
                <p class="center">专业权威</p>
            </li>
            <li class="feature2">
                <img class="pic" src="{% static 'images/feature2.png' %}"/>
                <p class="center">课程最新</p>
            </li>
            <li class="feature3">
                <img class="pic" src="{% static 'images/feature3.png' %}"/>
                <p class="center">名师授课</p>
            </li>
            <li class="feature4">
                <img class="pic" src="{% static 'images/feature4.png' %}"/>
                <p class="center">数据真实</p>
            </li>
        </ul>
    </div>
</section>
<!--feature end-->
<!--module1 start-->
<section>
    <div class="module">
        <div class="wp">
            <h1>公开课程</h1>
            <div class="module1 eachmod">
                <div class="module1_1 left">
                    <img width="228" height="614" src="{% static 'images/module1_1.jpg' %}"/>
                    <p class="fisrt_word">名师授课<br/>专业权威</p>
                    <a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>
                </div>
                <div class="right group_list">
                    <div class="module1_2 box">
                        <div class="imgslide2">
                            <ul class="imgs">
                            {% for banner_course in banner_courses %}
                                <li>
                                    <a href="{% url 'course:course_detail' banner_course.id %}">
                                        <img width="470" height="300" src="{{ MEDIA_URL }}{{ banner_course.image }}" />
                                    </a>
                                </li>
                            {% endfor %}
                            </ul>
                        </div>
                        <div class="unslider-arrow2 prev"></div>
                        <div class="unslider-arrow2 next"></div>
                    </div>
                    {% for course in courses %}
                        <div class="module1_{{ forloop.counter|add:2 }} box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <h2 title="django入门">{{ course.name }}</h2>
                                </a>
                                <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                <span class="fr">学习人数：{{ course.learn_nums }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl" title="慕课网">{{ course.organization.name }}</span>
                                <span class="star fr">{{ course.organization.fav_nums }}</span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
<!--module1 end-->
<!--module2 start-->
<section>
    <div class="module greybg">
        <div class="wp">
            <h1>课程机构</h1>
            <div class="module3 eachmod">
                <div class="module3_1 left">
                    <img width="228" height="463" src="{% static 'images/module3_1.jpg' %}"/>
                    <p class="fisrt_word">名校来袭<br/>权威认证</p>
                    <a class="more" href="{% url 'organization:organization_list' %}">查看更多机构 ></a>
                </div>
                <div class="right">
                    <ul>
                        {% for organization in organizations %}
                            <li class="{% if forloop.counter|divisibleby:5 %}five{% endif %}">
                                <a href="{% url 'organization:org_detail_home' organization.id %}">
                                    <div class="company">
                                        <img width="184" height="100" src="{{ MEDIA_URL }}{{ organization.image }}"/>
                                        <div class="score">
                                            <div class="circle">
                                                <h2>{{ organization.tag }}</h2>
                                            </div>
                                        </div>
                                    </div>
                                    <p><span class="key" title="慕课网">{{ organization.name }}</span></p>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!--module2 end-->
{% endblock %}

{% block custom_js %}
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

templates/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>注册|慕学在线</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

</head>
<body>
<div class="loginbox dialogbox">
    <h1>账号登录</h1>
    <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
    <div class="cont">
        <form id="jsLoginForm" autocomplete="off">
            <div class="box">
                <span class="word3">用户名</span>
                <input type="text" name="account_l" id="account_l" placeholder="手机号/邮箱" />
            </div>
            <div class="box">
                <span class="word2">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</span>
                <input type="password" name="password_l" id="password_l" placeholder="请输入您的密码"/>
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips"></div> <!--登录错误提示-->
            <div class="btns">
                <span><input type="checkbox" id="jsAutoLogin" />&nbsp;自动登录</span>
                <span class="forget btn fr">忘记密码</span>
            </div>
            <div class="button">
                <input type="button" value="登录" id="jsLoginBtn" />
            </div>
            <div class="btns">
                <span class="fr">没有账号？<span class="regist btn">立即注册</span></span>
            </div>
        </form>
    </div>
</div>
<div class="dialog" id="jsDialog">
    <!--提示弹出框-->
    <div class="successbox dialogbox" id="jsSuccessTips">
        <h1>成功提交</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <div class="cont">
            <h2>您的需求提交成功！</h2>
            <p></p>
        </div>
    </div>
    <div  class="noactivebox dialogbox" id="jsUnactiveForm" >
        <h1>邮件验证提示</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <div class="center">
            <img src="{% static 'images/send.png' %}"/>
            <p>我们已经向您的邮箱<span class="green" id="jsEmailToActive">12@13.com</span>发送了邮件，<br/>为保证您的账号安全，请及时验证邮箱</p>
            <p class="a"><a class="btn" id="jsGoToEmail" target="_blank" href="http://mail.qq.com">去邮箱验证</a></p>
            <p class="zy_success upmove"></p>
            <p style="display: none;" class="sendE2">没收到，您可以查看您的垃圾邮件和被过滤邮件，也可以再次发送验证邮件（<span class="c5c">60s</span>）</p>
            <p class="sendE">没收到，您可以查看您的垃圾邮件和被过滤邮件，<br/>也可以<span class="c5c green" id="jsSenEmailAgin" style="cursor: pointer;">再次发送验证邮件</span></p>
        </div>
    </div>
</div>

<div class="bg" id="dialogBg"></div>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">慕学在线，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>4001008031</span></li>
                <li><a href="{% url 'login' %}">[登录]</a></li>
                <li class="active"><a href="{% url 'register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="{% url 'index' %}"></a>
                <h1>用户注册</h1>
                <a class="index-font" href="{% url 'index' %}">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">

                        <li><a href=""><img width="483" height="472" src="{% static 'images/57a801860001c34b12000460.jpg' %}" /></a></li>

                        <li><a href=""><img width="483" height="472" src="{% static 'images/57a801860001c34b12000460.jpg' %}" /></a></li>

                        <li><a href=""><img width="483" height="472" src="{% static 'images/57a801860001c34b12000460.jpg' %}" /></a></li>

                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <div class="tab">
                    <!--<h2 class="active">手机注册</h2>-->
                    <h2>邮箱注册</h2>
                </div>
                <!--<div class="tab-form">-->
                    <!--<form id="mobile_register_form" autocomplete="off">-->
                        <!--<input type='hidden' name='csrfmiddlewaretoken' value='gTZljXgnpvxn0fKZ1XkWrM1PrCGSjiCZ' />-->
                        <!--<div class="form-group marb20">-->
                            <!--<label>手&nbsp;机&nbsp;号</label>-->
                            <!--<input id="jsRegMobile" name="account" type="text" placeholder="请输入您的手机号码" />-->
                        <!--</div>-->
                        <!--<div class="form-group marb20" id="jsRefreshCode">-->
                            <!--<label>验&nbsp;证&nbsp;码</label>-->
                            <!--<input autocomplete="off" class="form-control-captcha mobile-register-captcha" id="mobile-register-captcha_1" name="captcha_m_1" placeholder="请输入验证码" type="text" /> <input class="form-control-captcha mobile-register-captcha" id="mobile-register-captcha_0" name="captcha_m_0" placeholder="请输入验证码" type="hidden" value="29953bacf7005e8469388b449d97d00d523c1706" /> &nbsp;<img src="/captcha/image/29953bacf7005e8469388b449d97d00d523c1706/" alt="captcha" class="captcha" />-->
                        <!--</div>-->
                        <!--<div class="clearfix">-->
                            <!--<div class="form-group marb8 verify-code">-->
                                <!--<label>短信验证码</label>-->
                                <!--<input id="jsPhoneRegCaptcha" name="mobile_code" type="text" placeholder="输入手机验证码" />-->
                            <!--</div>-->
                            <!--<input class="verify-code-btn sendcode" id="jsSendCode" value="发送验证码">-->
                        <!--</div>-->
                        <!--<div class="form-group marb8">-->
                            <!--<label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>-->
                            <!--<input id="jsPhoneRegPwd" name="password_m" type="password" placeholder="请输入6-20位非中文字符密码" />-->
                        <!--</div>-->
                        <!--<div class="error btns" id="jsMobileTips"></div>-->
                        <!--<div class="auto-box marb8">-->

                        <!--</div>-->
                        <!--<input class="btn btn-green" id="jsMobileRegBtn" type="button" value="注册并登录" />-->
                    <!--</form>-->
                <!--</div>-->
                <div class="tab-form">
                    <form id="email_register_form" method="post" action="{% url 'register' %}" autocomplete="off">
                        <input type='hidden' name='csrfmiddlewaretoken' value='gTZljXgnpvxn0fKZ1XkWrM1PrCGSjiCZ' />
                        <div class="form-group marb20 {% if register_form.email.errors %}errorput{% endif %}">
                            <label>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</label>
                            <input  type="text" id="id_email" name="email" value="{{ register_form.email.value }}" placeholder="请输入您的邮箱地址" />
                        </div>
                        <div class="form-group marb8 {% if register_form.password.errors %}errorput{% endif %}">
                            <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                            <input type="password" id="id_password" name="password"  value="{{ register_form.password.value }}" placeholder="请输入6-20位非中文字符密码" />
                        </div>
                        <div class="form-group marb8 captcha1 {% if register_form.captcha.errors %}errorput{% endif %}">
                            <label>验&nbsp;证&nbsp;码</label>
                            {{ register_form.captcha }}
                            <img src="/captcha/image/2f3f82e5f7a054bf5caa93b9b0bb6cc308fb7011/" alt="captcha" class="captcha" />
                            <input id="id_captcha_0" name="captcha_0" type="hidden" value="2f3f82e5f7a054bf5caa93b9b0bb6cc308fb7011" />
                            <input autocomplete="off" id="id_captcha_1" name="captcha_1" type="text" />
                        </div>
                        <div class="error btns" id="jsEmailTips">
                            {% for key, error in register_form.errors.items %}
                                {{ error }}
                            {% endfor %}
                        </div>
                        <div class="auto-box marb8">
                        </div>
                        <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册并登录" />
                        <input type='hidden' name='csrfmiddlewaretoken' value='5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy' />
                        {% csrf_token %}
                    </form>
                </div>
                <p class="form-p">已有账号？<a href="{% url 'login' %}">[立即登录]</a></p>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>

templates/reset_pwd.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'modify_pwd' %}" method="post">
            <ul>

                <input type="hidden" name="email" value="{{ email }}">

                <li>
                    <span class="{% if reset_form.password1.errors %}errorput{% endif %}">新 密 码 ：</span>
                    <input type="password" name="password1" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li>
                    <span class="{% if reset_form.password2.errors %}errorput{% endif %}">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <div class="error btns" id="jsPasswdResetTips">
                    {% for key, error in reset_form.errors.items %}
                        {{ key }}:{{ error }}
                    {% endfor %}
                    {{ msg }}
                </div>
                <li class="button">
                    <input type="submit" value="提交" onclick="reset_password_form_submit()">
                </li>
            </ul>
            {% csrf_token %}
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="{% static 'images/check2.png' %}">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

templates/send_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>邮件已发送，请注意查收</p>
</body>
</html>