MxOnline2/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
import users.urls, organization.urls, course.urls
from users.views import IndexView, LoginView, LogoutView, RegisterView, ActiveUserView, ForgetPwdView, ResetPwdView, ModifyPwdView
from django.views.static import serve
from MxOnline2.settings import MEDIA_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    re_path('active/(?P<active_code>.*)/', ActiveUserView.as_view(), name='active_user'),
    path('forget/', ForgetPwdView.as_view(), name='forget_pwd'),
    re_path('reset/(?P<reset_code>.*?)/', ResetPwdView.as_view(), name='reset_pwd'),
    path('modify_pwd/', ModifyPwdView.as_view(), name='modify_pwd'),
    path('captcha/', include('captcha.urls')),

    # 配置图片路径、静态文件路径
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),

    path('users/', include(users.urls, namespace='users')),
    path('organization/', include(organization.urls, namespace='organization')),
    path('course/', include(course.urls, namespace='course')),
    # 富文本ckeditor配置url
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

handler404 = 'users.views.pag_not_found'
handler500 = 'users.views.page_error'

apps/course/urls.py
# coding:utf-8
from django.urls import path, re_path
from .views import CourseView, CourseListView, CourseInfoView, CourseCommentView, AddCommentView, VideoPlayView


app_name = 'course'

urlpatterns = [
    path('list/', CourseListView.as_view(), name='course_list'),
    re_path('course/(?P<course_id>\d+)/', CourseView.as_view(), name='course_detail'),
    re_path('info/(?P<course_id>\d+)/', CourseInfoView.as_view(), name='course_info'),
    re_path('comment/(?P<course_id>\d+)/', CourseCommentView.as_view(), name='course_comment'),
    path('add_comment/', AddCommentView.as_view(), name='add_comment'),
    re_path('video/(?P<video_id>\d+)/', VideoPlayView.as_view(), name='video_play'),
]

apps/organization/urls.py
# coding:utf-8
from django.urls import path, re_path
from .views import OrgListView, AddUserAskView, OrgDetailHomeView, OrgDetailCourseView, OrgDetailTeacherView,\
    OrgDetailDescView, AddFavView, TeacherListView, TeacherDetailView


app_name = 'organization'

urlpatterns = [
    path('list/', OrgListView.as_view(), name='organization_list'),
    path('add_ask/', AddUserAskView.as_view(), name='add_ask'),
    path('add_fav', AddFavView.as_view(), name='add_fav'),
    re_path('home/(?P<org_id>\d+)/', OrgDetailHomeView.as_view(), name='org_detail_home'),
    re_path('course/(?P<org_id>\d+)/', OrgDetailCourseView.as_view(), name='org_detail_course'),
    re_path('org_teacher/(?P<org_id>\d+)/', OrgDetailTeacherView.as_view(), name='org_detail_teacher'),
    re_path('desc/(?P<org_id>\d+)/', OrgDetailDescView.as_view(), name='org_detail_desc'),
    path('teacher/list/', TeacherListView.as_view(), name='teacher_list'),
    re_path('teacher/detail/(?P<teacher_id>\d+)/', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/users/urls.py
# coding:utf-8
from django.urls import path, re_path
from users.views import UserInfoView, UploadImageView, UpdatePwdView, \
    MyCourseView, MyFavOrgView, MyFavTeacherView, MyFavCourseView, MyMessageView


app_name = 'users'

urlpatterns = [
    path('info/', UserInfoView.as_view(), name='user_info'),
    path('upload/image/', UploadImageView.as_view(), name='upload_image'),
    path('update/pwd/', UpdatePwdView.as_view(), name='update_pwd'),

    path('mycourse/', MyCourseView.as_view(), name='mycourse'),
    path('myfav/org/', MyFavOrgView.as_view(), name='myfav_org'),
    path('myfav/teacher/', MyFavTeacherView.as_view(), name='myfav_teacher'),
    path('myfav/course/', MyFavCourseView.as_view(), name='myfav_course'),
    path('mymessage/', MyMessageView.as_view(), name='mymessage'),
]

apps/users/models.py
from django.db import models
import datetime

from django.contrib.auth.models import AbstractUser


# Create your models here.
class UserProfile(AbstractUser):
    GENDER_CHOICES = (
        ('male', '男'),
        ('female', '女'),
    )
    nick_name = models.CharField(verbose_name="昵称", default='', max_length=20)
    birthday = models.DateField(verbose_name="生日", null=True, blank=True)
    gender = models.CharField(verbose_name="性别", choices=GENDER_CHOICES, max_length=6, default='male')
    address = models.CharField(verbose_name="地址", max_length=100, default='')
    mobile = models.CharField(verbose_name="手机号", max_length=11, default='')
    image = models.ImageField(verbose_name="头像", upload_to='image/%Y/%m', default='')

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class EmailVerifyRecord(models.Model):
    VERIFY_RECORD_CHOICES = (
        ('register', '注册'),
        ('forget', '找回密码'),
        ('update_email', '修改邮箱'),
    )
    code = models.CharField(verbose_name="验证码", max_length=20)
    email = models.EmailField(verbose_name="邮箱", max_length=100)
    send_type = models.CharField(verbose_name="验证码类型", choices=VERIFY_RECORD_CHOICES, max_length=20)
    send_time = models.DateTimeField(verbose_name="", default=datetime.datetime.now)

    class Meta:
        verbose_name = "邮箱验证码"
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}({1})'.format(self.code, self.email)


class Banner(models.Model):
    title = models.CharField(verbose_name="标题", max_length=100)
    image = models.ImageField(verbose_name="轮播图", upload_to='banner/%Y/%m')
    url = models.URLField(verbose_name="访问地址", max_length=200)
    index = models.IntegerField(verbose_name="顺序", default=100)
    add_time = models.DateTimeField(verbose_name="添加时间", default=datetime.datetime.now)

    class Meta:
        verbose_name = "轮播图"
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}(位于第{1}位)'.format(self.title, self.index)

apps/users/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=6)


# 注册页表单多了一个验证码字段captcha，从安装的第三方库django-simple-captcha引入
class RegisterForm(forms.Form):
    email = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=6)
    captcha = CaptchaField(required=True, error_messages={'invalid': '验证码错误'})


class ForgetPwdForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(required=True, error_messages={'invalid': '验证码错误'})


class ResetPwdForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=6)
    password2 = forms.CharField(required=True, min_length=6)


class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nick_name', 'birthday', 'gender', 'address', 'mobile']

apps/users/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth.backends import ModelBackend
from users.models import UserProfile, EmailVerifyRecord, Banner
from course.models import Course
from operation.models import UserCourse, UserFavorite, UserMessage
from organization.models import Organization, Teacher
from django.db.models import Q
from .forms import LoginForm, RegisterForm, ForgetPwdForm, ResetPwdForm, UserInfoForm
from utils import send_email
from .forms import UploadImageForm
from django.http import HttpResponse
import json
from utils.mixin_utils import LoginRequiredMixin
from django.core.paginator import Paginator


# 首页视图
class IndexView(View):
    def get(self, request):
        all_banners = Banner.objects.all().order_by('index')
        courses = Course.objects.filter(is_banner=False)[:6]
        banner_courses = Course.objects.filter(is_banner=True)[:3]
        organizations = Organization.objects.all()[:15]
        context = {
            'all_banners': all_banners,
            'courses': courses,
            'banner_courses': banner_courses,
            'organizations': organizations,
        }
        return render(request, 'index.html', context=context)


# 复写ModelBackend的authenticate方法。
# django自带的authenticate方法只能认证用户名，现在希望用户名和邮箱都可以登录.
"""
Authenticates against settings.AUTH_USER_MODEL.

def authenticate(self, request, username=None, password=None, **kwargs):
    if username is None:
        username = kwargs.get(UserModel.USERNAME_FIELD)
    try:
        user = UserModel._default_manager.get_by_natural_key(username)
    except UserModel.DoesNotExist:
        # Run the default password hasher once to reduce the timing
        # difference between an existing and a nonexistent user (#20760).
        UserModel().set_password(password)
    else:
        if user.check_password(password) and self.user_can_authenticate(user):
            return user
"""


class CustomBackend(ModelBackend):
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            user = UserProfile.objects.get(Q(username=username) | Q(email=username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None


# 登录页视图
class LoginView(View):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        # 先实例化一个Form对象，从request.POST所构建的字典中bound绑定数据
        # 然后调用Form.is_valid()方法，判断从前端传过来的数据是否合法
        # 如果数据合法，获取用户名和密码，然后进行后台验证。如果验证成功并且用户已激活则登录并转到主页，否则返回错误信息。
        # 如果数据不合法，则返回login页，并将用户填写的数据也放进去，且包含表单错误信息
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user_name = request.POST.get('username', None)
            pass_word = request.POST.get('password', None)
            user = authenticate(username=user_name, password=pass_word)
            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('index'))
                else:
                    return render(request, 'login.html', {'login_form': login_form, 'msg': '用户名或密码错误'})
            else:
                return render(request, 'login.html', {'login_form': login_form, 'msg': '用户名或密码错误'})
        else:
            return render(request, 'login.html', {'login_form': login_form})


# 登出
class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('index'))


# 注册页视图
class RegisterView(View):
    def get(self, request):
        return render(request, 'register.html')

    def post(self, request):
        """业务逻辑：
        首先实例化一个Form对象，从request.POST中绑定数据，判断其是否合法
        如果合法，获取email和password，然后判断email是否已经存在，如果存在，则返回注册页并渲染一个信息。
        如果email可用，实例化一个UserProfile对象，并将数据保存至数据库，然后发送注册邮件，并然后登录页。
        如果form不合法，返回register页
        """
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            user_name = request.POST.get('email', None)
            pass_word = request.POST.get('password', None)
            if UserProfile.objects.filter(email=user_name):
                return render(request, 'register.html', {'register_form': 'register_form', 'msg': '邮箱已存在'})
            else:
                user_profile = UserProfile()
                user_profile.email = user_name
                user_profile.username = user_name
                user_profile.password = make_password(pass_word)
                user_profile.is_active = False
                user_profile.save()
                # 发送邮箱验证码
                send_email.send_user_email(email=user_name, send_type='register')
                return render(request, 'login.html')
        else:
            return render(request, 'register.html', {'register_form': register_form})


# 激活用户页视图
class ActiveUserView(View):
    """业务逻辑：
    获取从用户端传过来的code，判断数据库中是否存在，如果存在，激活该用户,并跳转到登陆页。否则跳转到激活失败页面
    """
    def get(self, request, active_code):
        email_record = EmailVerifyRecord.objects.filter(code=active_code)
        if email_record:
            # 这里有极小可能但是不排除出现两个验证码相同的情况，如果存在，说明之前的用户A已经激活，当前的用户B未激活，
            # 现在,直接将所有符合验证码的用户都激活就行了
            for record in email_record:
                email = record.email
                user_profile = UserProfile.objects.get(email=email)
                user_profile.is_active = True
                user_profile.save()
        else:
            return render(request, 'active_fail.html')
        return render(request, 'login.html')


# 忘记密码页视图
class ForgetPwdView(View):
    def get(self, request):
        forget_form = ForgetPwdForm()
        return render(request, 'forget_pwd.html', {'forget_form': forget_form})

    def post(self, request):
        forget_form = ForgetPwdForm(request.POST)
        if forget_form.is_valid():
            email = request.POST.get('email', None)
            if UserProfile.objects.filter(email=email):
                send_email.send_user_email(email=email, send_type='forget')
                # 成功之后要用重定向,否则直接render的话,地址栏还是显示的/forget/
                return render(request, "login.html", {"msg": "重置密码邮件已发送,请注意查收"})
            else:
                return render(request, 'forget_pwd.html', {'forget_form': forget_form, 'msg': '邮箱错误'})
        else:
            return render(request, 'forget_pwd.html', {'forget_form': forget_form})


# 重置密码页视图
class ResetPwdView(View):
    def get(self, request, reset_code):
        reset_record = EmailVerifyRecord.objects.filter(code=reset_code)
        if reset_record:
            for record in reset_record:
                email = record.email
                return render(request, 'reset_pwd.html', {'email': email})
        else:
            return render(request, 'active_fail.html')


# 修改密码页视图
# 紧跟ResetPwdView，由于重置密码的链接中含有一个reset_code，所以，提交表单时的post方式并不适应
# 这里新建一个View，专门用来处理reset_pwd.html页面提交过来的form信息
class ModifyPwdView(View):
    def post(self, request):
        reset_form = ResetPwdForm(request.POST)
        email = request.POST.get('email', None)
        if reset_form.is_valid():
            password1 = request.POST.get('password1', None)
            password2 = request.POST.get('password2', None)
            if password1 == password2:
                user_profile = UserProfile.objects.get(email=email)
                user_profile.password = make_password(password1)
                user_profile.save()
                return HttpResponseRedirect(reverse('login'))
            else:
                return render(request, 'reset_pwd.html', {'email': email, 'reset_form': reset_form, 'msg': '两次输入的密码不一致'})
        else:
            return render(request, 'reset_pwd.html', {'email': email, 'reset_form': reset_form})


# 用户中心页
class UserInfoView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'users/usercenter_info.html')

    def post(self, request):
        user_info_form = UserInfoForm(request.POST, instance=request.user)
        if user_info_form.is_valid():
            user_info_form.save()
            return HttpResponse('{"status": "success"}', content_type='application/json')
        else:
            return HttpResponse(json.dumps(user_info_form.errors), content_type='application/json')


class UploadImageView(View):
    def post(self, request):
        upload_image_form = UploadImageForm(request.POST, request.FILES)
        if upload_image_form.is_valid():
            image = upload_image_form.cleaned_data['image']
            request.user.image = image
            request.user.save()
            return HttpResponse('{"status": "success"}', content_type='application/json')
        else:
            return HttpResponse('{"status": "fail"}', content_type='application/json')


class UpdatePwdView(View):
    def post(self, request):
        reset_form = ResetPwdForm(request.POST)
        if reset_form.is_valid():
            password1 = request.POST.get('password1', None)
            password2 = request.POST.get('password2', None)
            if password1 == password2:
                user_profile = request.user
                user_profile.password = make_password(password1)
                user_profile.save()
                return HttpResponse('{"status": "success"}', content_type='application/json')
            else:
                return HttpResponse('{"status": "fail", "msg": "密码不一致"}',  content_type='application/json')
        else:
            return HttpResponse(json.dumps(reset_form.errors), content_type='application/json')


class MyCourseView(View):
    def get(self, request):
        user_courses = UserCourse.objects.filter(user=request.user)
        context = {
            'user_courses': user_courses,
        }

templates/users/usercenter_fav_course.html
{% extends 'users/usercenter_base.html' %}
{% load staticfiles %}
{% block title %}
我的收藏
{% endblock %}
{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
            <li>我的收藏</li>
        </ul>
    </div>
</section>
{% endblock %}
{% block right_content %}
<div class="right" >
    <div class="personal_des Releasecont">
        <div class="head">
            <h1>我的收藏</h1>
        </div>
    </div>
    <div class="personal_des permessage">
        <div class="head">
            <ul class="tab_header messagehead">
                <li><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                <li class="active"><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
            </ul>
        </div>
        <div class="companycenter">
            <div class="group_list brief">
            {% for my_fav_course in my_fav_courses %}
                <div class="module1_5 box">
                    <a href="{% url 'course:course_detail' my_fav_course.id %}">
                        <img width="214" height="190" src="{{ MEDIA_URL}}{{ my_fav_course.image }}"/>
                    </a>
                    <div class="des">
                        <a href="{% url 'course:course_detail' my_fav_course.id %}"><h2>{{ my_fav_course.name }}</h2></a>
                        <span class="fl">时长：<i class="key">{{ my_fav_course.learn_times }}</i></span>
                        <span class="fr">学习人数：{{ my_fav_course.learn_nums }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{ my_fav_course.organization.name }}</span>
                        <span class="delete-group fr jsDeleteFav_course" data-favid="{{ my_fav_course.id }}"></span>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/usercenter_fav_org.html
{% extends 'users/usercenter_base.html' %}
{% load staticfiles %}
{% block title %}
我的课程
{% endblock %}
{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
            <li>我的收藏</li>
        </ul>
    </div>
</section>
{% endblock %}
{% block right_content %}
<div class="right" >
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>

        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li class="active"><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                    <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                    <li><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                </ul>
            </div>
            <div class="messagelist">
                {% for my_fav_org in my_fav_orgs %}
                <div class="messages butler_list company company-fav-box">
                    <dl class="des fr">
                        <dt>
                            <a href="{% url 'organization:org_detail_home' my_fav_org.id %}">
                                <img width="160" height="90" src="{{ MEDIA_URL }}{{ my_fav_org.image }}"/>
                            </a>
                        </dt>
                        <dd>
                            <h1><a href="{% url 'organization:org_detail_home' my_fav_org.id %}">{{ my_fav_org.name }}</a></h1>
                            <div class="pic fl" style="width:auto;">
                            {% if my_fav_org.is_authentication %}
                                <img src="{% static 'images/authentication.png' %}"/>
                            {% endif %}
                            {% if my_fav_org.is_gold %}
                                <img src="{% static 'images/gold.png' %}"/>
                            {% endif %}
                            </div>
                            <span class="c8 clear">{{ my_fav_org.city.name }}</span>
                            <div class="delete jsDeleteFav_org" data-favid="{{ my_fav_org.id }}"></div>
                        </dd>
                    </dl>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/users/usercenter_fav_teacher.html
{% extends 'users/usercenter_base.html' %}
{% load staticfiles %}
{% block title %}
我的收藏
{% endblock %}
{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
            <li>我的收藏</li>
        </ul>
    </div>
</section>
{% endblock %}
{% block right_content %}
<div class="right" >
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                    <li class="active"><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                    <li><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                </ul>
            </div>
            <div class="messagelist">
                {% for my_fav_teacher in my_fav_teachers %}
                    <div class=" butler_list butler-fav-box">
                        <dl class="des users">
                            <dt>
                                <a href="{% url 'organization:teacher_detail' my_fav_teacher.id %}">
                                    <img width="100" height="100" src="{{ MEDIA_URL }}{{ my_fav_teacher.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="{% url 'organization:teacher_detail' my_fav_teacher.id %}">
                                        {{ my_fav_teacher.name }}<span class="key">认证教师</span>
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">工作年限：<span>{{ my_fav_teacher.work_year }}年</span></li>
                                    <li class="c7">课程数：<span>{{ my_fav_teacher.get_course_nums }}</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">工作公司：<span>{{ my_fav_teacher.work_company }}</span></li>
                                    <li class="c7">公司职位：<span>{{ my_fav_teacher.work_position }}</span></li>
                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav_teacher" data-favid="{{ my_fav_teacher.id }}"></div>
                        </dl>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/users/usercenter_info.html
{% extends 'users/usercenter_base.html' %}
{% load staticfiles %}
{% block title %}
个人中心
{% endblock %}
<!--crumbs start-->
{% block custom_bread %}
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
            <li>个人信息</li>
        </ul>
    </div>
</section>
{% endblock %}

{% block right_content %}
<div class="right">
    <div class="personal_des ">
        <div class="head" style="border:1px solid #eaeaea;">
            <h1>个人信息</h1>
        </div>
        <div class="inforcon">
            <div class="left" style="width:242px;">
                <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{% url 'users:upload_image' %}" target='frameFile'>
                    <label class="changearea" for="avatarUp">
                        <span id="avatardiv" class="pic">
                            <img width="100" height="100" class="js-img-show" id="avatarShow" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                        </span>
                        <span class="fl upload-inp-box" style="margin-left:70px;">
                            <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                            <input type="file" name="image" id="avatarUp" class="js-img-up"/>
                        </span>
                    </label>
                {% csrf_token %}
                </form>
                <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                    <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                </div>
            </div>
            <form class="perinform" id="jsEditUserForm" autocomplete="off">
                <ul class="right">
                    <li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                       <input type="text" name="nick_name" id="nick_name" value="{{ request.user.nick_name }}" maxlength="10">
                        <i class="error-tips"></i>
                    </li>
                    <li>生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：
                       <input type="text" id="birth_day" name="birday" value="{{ request.user.birthday }}" readonly="readonly"/>
                        <i class="error-tips"></i>
                    </li>
                    <li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
                        <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio"  name="gender" value="male" {% if request.user.gender == 'male' %}checked="checked"{% endif %}>男</label>
                        <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="female" {% if request.user.gender == 'female' %}checked="checked"{% endif %}>女</label>
                    </li>
                    <li class="p_infor_city">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：
                        <input type="text" name="address" id="address" placeholder="请输入你的地址" value="{{ request.user.address }}" maxlength="10">
                        <i class="error-tips"></i>
                    </li>
                    <li>手&nbsp;&nbsp;机&nbsp;&nbsp;号：
                        <input type="text" name="mobile" id="mobile" placeholder="请输入你的手机号码" value="{{ request.user.mobile }}" maxlength="10">
                    </li>
                    <li>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱：
                        <input class="borderno" type="text" name="email" readonly="readonly" value="{{ request.user.email }}"/>
                        <span class="green changeemai_btn">[修改]</span>
                    </li>
                    <li class="button heibtn">
                        <input type="button" id="jsEditUserBtn" value="保存">
                    </li>
                </ul>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>
{% endblock %}